### ISSUE TITLE
Erreur dans les tests frontend

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2108]
les tests du wizard generent des erreurs 
```
 Error: Not implemented: window.scrollTo
          at module.exports (/Users/lionel/Code/beta.gouv/code-du-travail-numerique/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at scrollTo (/Users/lionel/Code/beta.gouv/code-du-travail-numerique/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:594:7)
          at /Users/lionel/Code/beta.gouv/code-du-travail-numerique/packages/code-du-travail-frontend/src/outils/common/Wizard.js:25:14
          at commitHookEffectList (/Users/lionel/Code/beta.gouv/code-du-travail-numerique/node_modules/react-dom/cjs/react-dom.development.js:22030:26)
          at commitPassiveHookEffects (/Users/lionel/Code/beta.gouv/code-du-travail-numerique/node_modules/react-dom/cjs/react-dom.development.js:22064:11)
          at HTMLUnknownElement.callCallback (/Users/lionel/Code/beta.gouv/code-du-travail-numerique/node_modules/react-dom/cjs/react-dom.development.js:336:14)
          at invokeEventListeners (/Users/lionel/Code/beta.gouv/code-du-travail-numerique/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
          at HTMLUnknownElementImpl._dispatch (/Users/lionel/Code/beta.gouv/code-du-travail-numerique/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/lionel/Code/beta.gouv/code-du-travail-numerique/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/lionel/Code/beta.gouv/code-du-travail-numerique/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27) undefined
```
il faudrait mocker window..scrollTo dans les tests ou s'assurer que la fonction existe avant de l'appeller

**Comment by lionelB** [comment]
done in #2175
