### ISSUE TITLE
Fix erreur dans les logs "ImageError: "url" parameter is valid but upstream response is invalid"

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5708]
```
024-03-20T09:18:03.427036892Z  ⨯ upstream image response failed for /static/assets/img/ministere_logo.jpeg ResponseAborted
2024-03-20T09:18:03.427064479Z     at Object.fetch (node:internal/deps/undici/undici:11576:11)
2024-03-20T09:18:03.427070903Z     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
2024-03-20T09:18:03.427076860Z     at async /app/node_modules/next/dist/server/next-server.js:596:35
    at async imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:576:13)
2024-03-20T09:18:03.427099349Z     at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:176:65)
2024-03-20T09:18:03.427106697Z     at async /app/node_modules/next/dist/server/response-cache/index.js:90:36
2024-03-20T09:18:03.427111286Z     at async /app/node_modules/next/dist/lib/batcher.js:41:32
2024-03-20T09:18:03.428703012Z ImageError: "url" parameter is valid but upstream response is invalid
2024-03-20T09:18:03.428714200Z     at imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:588:19)
2024-03-20T09:18:03.428719231Z     at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:176:65)
2024-03-20T09:18:03.428722613Z     at async /app/node_modules/next/dist/server/response-cache/index.js:90:36
2024-03-20T09:18:03.428726152Z     at async /app/node_modules/next/dist/lib/batcher.js:41:32 {
2024-03-20T09:18:03.428729558Z   statusCode: 500
2024-03-20T09:18:03.428732884Z }
```

**Comment by m-maillot** [comment]
Utiliser le format PNG pour essayer : https://fr.wikipedia.org/wiki/Minist%C3%A8re_du_Travail_(France)#/media/Fichier:Logo-travail-emploi.png
